### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by yeroslaviz** [www-bioinfo-org/CNCI#5]
When running the `compare.py` script I get the following error:

```
Classification start:
Traceback (most recent call last):
  File "/local/Assa/software/CNCI/compare.py", line 187, in <module>
    combined_gtf_input, cuffcompare_outdir)
  File "/local/Assa/software/CNCI/compare.py", line 114, in fetch_gtfs
    erase_strand(coding_ref_input,coding_ref)
  File "/local/Assa/software/CNCI/compare.py", line 107, in erase_strand
    result.update_col(7,'+')
  File "/local/Assa/software/CNCI/Table.py", line 451, in update_col
    self.data[index][the_number]=new_value
IndexError: list assignment index out of range
```

I was wondering if you can tell me why this happen or at least where to start looking for the problem.

thanks
Assa

**Comment by Lee211** [comment]
i have the same problem.

**Comment by Tyrion233** [comment]
make sure your fasta file have no "head lines" before ">"

**Comment by Jmac1697** [comment]
(cnci_env) jose@DESKTOP-SD5R7G5:/mnt/c/Users/josej/Desktop/New_folder/CNCI-master$ python compare.py -c /mnt/c/Users/josej/RNA_resources/ENSEMBL/filtered_Danio_rerio_GRCz11.110_only_coding.gtf -n /mnt/c/Users/josej/RNA_resources/gffcmp.combined.gtf -i /mnt/c/Users/josej/Desktop/New_folder/processed_reads/stringtie_output_withGTF/merged_transcripts_withGTF.gtf -o /mnt/c/Users/josej/Desktop/New_folder/processed_reads/CNCI/withGTF
Classification start:
Traceback (most recent call last):
  File "compare.py", line 187, in <module>
    combined_gtf_input, cuffcompare_outdir)
  File "compare.py", line 116, in fetch_gtfs
    erase_strand(combined_gtf_input,combined_gtf)
  File "compare.py", line 107, in erase_strand
    result.update_col(7,'+')
  File "/mnt/c/Users/josej/Desktop/New_folder/CNCI-master/Table.py", line 451, in update_col
    self.data[index][the_number]=new_value
IndexError: list assignment index out of range
(cnci_env) jose@DESKTOP-SD5R7G5:/mnt/c/Users/josej/Desktop/New_folder/CNCI-master$ python compare.py -c /mnt/c/Users/josej/RNA_resources/ENSEMBL/filtered_Danio_rerio_GRCz11.110_only_coding.gtf -n /mnt/c/Users/josej/RNA_resources/gffcmp.combined.gtf -i /mnt/c/Users/josej/Desktop/New_folder/processed_reads/stringtie_output_withGTF/merged_transcripts_withGTF.gtf -o /mnt/c/Users/josej/Desktop/New_folder/processed_reads/CNCI/withGTF
Classification start:
Input genes:  40108
Running Cuffcompare ...
Classifying based on Cuffcompare results:
Known coding genes: 23543
Known lincRNA genes: 3740
Undefinable genes: 2404
Potentially novel genes: 10413
Genes missing classification by cuffcompare: 20
Saving gtf files ..

I had the same issue. turns out the assembled gtf had two lines at the top that started with #. 

# stringtie --merge -G /mnt/c/Users/josej/RNA_resources/ENSEMBL/Danio_rerio.GRCz11.110.gtf -o merged_transcripts_withGTF.gtf gtf_list.txt
# StringTie version 3.0.0
1	StringTie	transcript	6408	12027	1000	-	.	gene_id "MSTRG.1"; transcript_id "ENSDART00000164359"; gene_name "rpl24"; ref_gene_id "ENSDARG00000099104"; 

once i removed those it worked.
